eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
    lease-renewal-interval-in-seconds: 10
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    healthcheck:
      enabled: true
    register-with-eureka: true
zuul:
  routes:
    EES-MS-USERS:
      path: /api/v1/**
    user-service:
      url: http://localhost:9190
    EES-MS-ACCOUNTING:
      path: /api/v1/**
    accounting-service:
      url: http://localhost:9191
  sensitive-headers:
    - Cookie
    - Set-Cookie
  add-proxy-headers: false
  host:
    connect-timeout-millis: 90000
    socket-timeout-millis: 90000
ribbon:
  eureka:
    enabled: true