server:
  port: 9010
spring:
  profiles:
    active:
      - ${ENVIRONMENT}
  application:
    name: EES-API-GATEWAY
  main:
    web-application-type: reactive #or remove spring-boot-starter-web dependency
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
      routes:
        - id: EES-MS-USERS
          uri: lb://EES-MS-USERS
          predicates:
            - Path=/user-service/**
#          filters:
#          - name: CircuitBreaker
#            args:
#              name: EES-MS-USERS-BREAKER
#              fallbackuri: forward:/userServiceFallBack
        - id: EES-MS-ACCOUNTING
          uri: lb://EES-MS-ACCOUNTING
          predicates:
            - Path=/accounting-service/**
#          filters:
#          - name: CircuitBreaker
#            args:
#              name: EES-MS-ACCOUNTING-BREAKER
#              fallbackuri: forward:/accountingServiceFallBack