apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: ees-ms-cloud-gateway-app
  labels:
    app: ees-ms-cloud-gateway-app
spec:
  selector:
    matchLabels:
      app: ees-ms-cloud-gateway-app
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: ees-ms-cloud-gateway-app
    spec:
      containers:
        - name: ees-ms-cloud-gateway-app
          image: enexse/ees-ms-cloud-gateway:latest # Image that will be used to containers in the cluster
          imagePullPolicy: Always
          ports:
            - containerPort: 9010 # The port that the container is running on in the cluster
          env:
          - name: EUREKA_SERVER_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: eureka-cm
                key: eureka_service_address

---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata:
  name: ees-ms-cloud-gateway-svc # Metadata of the resource kind we are creating
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "https"
spec:
  selector:
    app: ees-ms-cloud-gateway-app
  ports:
    - port: 80 # The port that the service is running on in the cluster
      protocol: TCP
      targetPort: 9010 # The port exposed by the service
  type: LoadBalancer # type of the service.
